sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
os:
  - linux
script:
  - cargo test --all
  - cargo test --features log-events --all
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --features unstable --all; fi"
  - cargo build --all
